In [2]:
import os
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [147]:
def count_words_in_go_files(folder_path, words_dict):
    word_search_counts = {word: 0 for word in words_dict.keys()}
    word_markup_counts = words_dict.copy()
    
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, words_dict.keys())) + r')\b')
    
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith('.go'):
                file_path = os.path.join(root, file)
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        matches = pattern.findall(content)
                        for word in matches:
                            word_search_counts[word] += 1
                except (UnicodeDecodeError, PermissionError) as e:
                    print(f"Ошибка при обработке файла {file_path}: {e}")
    
    # Создаем DataFrame
    df = pd.DataFrame({
        'Word': list(word_search_counts.keys()),
        'Count Search': list(word_search_counts.values()),
        'Count Markup': [word_markup_counts[word] for word in word_search_counts.keys()]
    })
    
    # Вычисляем Ratio
    df['Ratio'] = df['Count Search'] / df['Count Markup']
    
    median = df['Ratio'].median()
    mad = (df['Ratio'] - median).abs().median()
    threshold = 3
    df['IsOutlier_MAD'] = (df['Ratio'] - median).abs() > (threshold * mad)
    df['ratio<30'] = df['Ratio']<30

    
    
    # Сортируем по Ratio (по убыванию)
    df_sorted = df.sort_values(by='Ratio', ascending=False)
    df_sorted.reset_index(drop=True, inplace=True)
    
    return df_sorted

In [148]:
global_array = np.array([])
one_array = np.array([])

In [149]:
def analyze(folder, words):
    result_df = count_words_in_go_files(folder, words)

    mean_row = pd.DataFrame({
        'Word': ['MEAN'],
        'Count Search': [result_df['Count Search'].mean()],
        'Count Markup': [result_df['Count Markup'].mean()],
        'Ratio': [result_df['Ratio'].mean()]
    })
    
    global global_array
    global_array = np.append(global_array, result_df['Ratio'].values)

    display(result_df)
    display(mean_row)
    s1 = iterate_over_column(result_df[result_df['ratio<30']]["Count Search"], dt1)
    s2 = iterate_over_column(result_df[result_df['ratio<30']]["Count Markup"], dt2)
    print(s1/s2)

In [161]:
# время выбора (просмотра варианта)
dt1 = 4000
# время выбора (просмотр варианта), когда есть ранжирование
dt2 = 3000
# время осознания 
dt = 500
# время на навигацию
dd = 100

In [162]:
def iterate_over_column(column: pd.Series, dtX):
    s = 0
    for val in column:
        if val == 1:
            s += val * 0 + dt + dd
        else:
            s += val * dtX + dt + dd
    return s

In [163]:
folder = 'e:\\phd\\test_repos_graphql2\\boost\\'
words = {
    "DealUpdate": 1, 
    "StorageAskUpdate": 1, 
    "FundsMoveToEscrow": 1, 
    "DealFailPaused": 1, 
    "DealRetryPaused": 1, 
    "DealCancel": 1, 
    "Mpool": 1, 
    "FundsLogs": 1, 
    "ProposalLogs": 1, 
    "LegacyDeals": 1, 
    "Deals": 1, 
    "LegacyDeal": 1, 
    "Deal": 2, 
    "DealNew": 1, 
    "DealsCount": 1, 
    "StorageAsk": 1, 
    "DealPublishNow": 1, 
    "DealPublish": 1,
    "Epoch": 1,
    "Funds": 1,
    "ProposalLogsCount": 1,
    "SealingPipeline": 1,
    "Storage": 1,
    "Transfers": 1,
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,Deals,56,1,56.0,True,False
1,StorageAsk,32,1,32.0,True,False
2,Storage,26,1,26.0,True,True
3,Deal,16,2,8.0,True,True
4,Epoch,7,1,7.0,True,True
5,ProposalLogs,5,1,5.0,True,True
6,FundsLogs,4,1,4.0,True,True
7,Transfers,4,1,4.0,True,True
8,DealNew,2,1,2.0,False,True
9,DealPublish,2,1,2.0,False,True
10,Funds,2,1,2.0,False,True
11,SealingPipeline,2,1,2.0,False,True
12,Mpool,1,1,1.0,False,True
13,LegacyDeals,1,1,1.0,False,True
14,DealCancel,1,1,1.0,False,True
15,LegacyDeal,1,1,1.0,False,True
16,StorageAskUpdate,1,1,1.0,False,True
17,DealsCount,1,1,1.0,False,True
18,DealRetryPaused,1,1,1.0,False,True
19,DealPublishNow,1,1,1.0,False,True
20,DealFailPaused,1,1,1.0,False,True
21,ProposalLogsCount,1,1,1.0,False,True
22,FundsMoveToEscrow,1,1,1.0,False,True
23,DealUpdate,1,1,1.0,False,True

   Word  Count Search  Count Markup  Ratio
0  MEAN      7.083333      1.041667   6.75

15.270833333333334

In [164]:
folder = 'e:\\phd\\test_repos_graphql2\\circuit\\'
words = {
    "Secrets": 2, 
    "Services": 2, 
    "Releases": 2, 
    "EnvsDeployedIn": 2, 
    "Features": 2, 
    "GetGitCommits": 1, 
    "BookmarkProject": 1, 
    "UpdateProjectEnvironments": 1, 
    "UpdateUserPermissions": 1, 
    "DeleteProjectExtension": 1, 
    "UpdateProjectExtension": 1, 
    "CreateProjectExtension": 1, 
    "DeleteExtension": 1, 
    "UpdateExtension": 1, 
    "CreateExtension": 1, 
    "ImportSecrets": 1, 
    "DeleteSecret": 1, 
    "UpdateSecret": 1, 
    "CreateSecret": 1, 
    "DeleteEnvironment": 1,
    "UpdateEnvironment": 1, 
    "CreateEnvironment": 1, 
    "DeleteServiceSpec": 1, 
    "UpdateServiceSpec": 1, 
    "CreateServiceSpec": 1, 
    "ImportServices": 1, 
    "DeleteService": 1, 
    "UpdateService": 1, 
    "CreateService": 1, 
    "StopRelease": 1,
    "CreateRelease": 1, 
    "UpdateProject": 1, 
    "CreateProject": 1, 
    "Permissions": 1, 
    "ReleaseExtensions": 1, 
    "ProjectExtensions": 1, 
    "Extensions": 1, 
    "Secret": 1, 
    "ExportSecrets": 1, 
    "Environments": 1, 
    "ServiceSpecs": 1, 
    "Users": 1, 
    "User": 1, 
    "Bookmarked": 1, 
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,User,2577,1,2577.0,True,False
1,Secret,660,1,660.0,True,False
2,Extensions,379,1,379.0,True,False
3,Permissions,371,1,371.0,True,False
4,Services,541,2,270.5,True,False
5,CreateProject,180,1,180.0,True,False
6,CreateEnvironment,164,1,164.0,True,False
7,Secrets,299,2,149.5,True,False
8,CreateService,143,1,143.0,True,False
9,Users,122,1,122.0,True,False
10,CreateSecret,99,1,99.0,True,False
11,UpdateService,82,1,82.0,False,False
12,UpdateProject,66,1,66.0,False,False
13,CreateExtension,61,1,61.0,False,False
14,CreateServiceSpec,55,1,55.0,False,False
15,UpdateSecret,54,1,54.0,False,False
16,CreateProjectExtension,54,1,54.0,False,False
17,UpdateEnvironment,41,1,41.0,False,False
18,DeleteService,39,1,39.0,False,False
19,CreateRelease,37,1,37.0,False,False
20,Environments,33,1,33.0,False,False
21,Features,62,2,31.0,False,False
22,DeleteSecret,27,1,27.0,False,True
23,ProjectExtensions,26,1,26.0,False,True
24,DeleteEnvironment,21,1,21.0,False,True
25,Bookmarked,17,1,17.0,False,True
26,ImportServices,12,1,12.0,False,True
27,ReleaseExtensions,12,1,12.0,False,True
28,StopRelease,12,1,12.0,False,True
29,ImportSecrets,10,1,10.0,False,True
30,UpdateProjectEnvironments,10,1,10.0,False,True
31,Releases,19,2,9.5,False,True
32,UpdateUserPermissions,9,1,9.0,False,True
33,DeleteServiceSpec,9,1,9.0,False,True
34,DeleteProjectExtension,8,1,8.0,False,True
35,UpdateProjectExtension,8,1,8.0,False,True
36,UpdateServiceSpec,8,1,8.0,False,True
37,BookmarkProject,8,1,8.0,False,True
38,DeleteExtension,7,1,7.0,False,True
39,ExportSecrets,7,1,7.0,False,True
40,UpdateExtension,7,1,7.0,False,True
41,ServiceSpecs,4,1,4.0,False,True
42,EnvsDeployedIn,8,2,4.0,False,True
43,GetGitCommits,3,1,3.0,False,True

   Word  Count Search  Count Markup       Ratio
0  MEAN    144.795455      1.113636  134.238636

40.523809523809526

In [165]:
folder = 'e:\\phd\\test_repos_graphql2\\core-geth\\'
words = {
    "SendRawTransaction": 2,
    "Logs": 2,
    "Transaction": 2,
    "Blocks": 1,
    "Block": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "OmmerAt": 1,
    "Miner": 1,
    "CreatedContract": 1,
    "Account": 1,
    "Storage": 1,
    "Status": 1,
    "Nonce": 1,
    "Hash": 1,
    "TransactionCount": 1,
    "ChainID": 1,
    "MaxPriorityFeePerGas": 1,
    "GasPrice": 1,
    "Transactions": 1,
    "ExcessBlobGas": 1,
    "BlobGasUsed": 1,
    "Withdrawals": 1,
    "WithdrawalsRoot": 1,
    "Raw": 1,
    "RawHeader": 1,
    "TotalDifficulty": 1,
    "LogsBloom": 1,
    "ExtraData": 1,
    "Ommers": 1,
    "OmmerCount": 1,
    "OmmerHash": 1,
    "ReceiptsRoot": 1,
    "StateRoot": 1,
    "TransactionsRoot": 1,
    "MixHash": 1,
    "Timestamp": 1,
    "Difficulty": 1,
    "Parent": 1,
    "NextBaseFeePerGas": 1,
    "BaseFeePerGas": 1,
    "GasUsed": 1,
    "GasLimit": 1,
    "Number": 1,
    "YParity": 1,
    "AccessList": 1,
    "Type": 1,
    "BlobGasPrice": 1,
    "CumulativeGasUsed": 1,
    "Index": 1,
    "Value": 1,
    "EffectiveTip": 1,
    "BlobVersionedHashes": 1,
    "MaxFeePerBlobGas": 1,
    "MaxFeePerGas": 1,
    "EffectiveGasPrice": 1,
    "Gas": 1,
    "InputData": 1
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,Hash,6364,1,6364.0,True,False
1,Number,1446,1,1446.0,True,False
2,Value,1096,1,1096.0,True,False
3,Type,1049,1,1049.0,True,False
4,Block,770,1,770.0,True,False
5,Nonce,712,1,712.0,True,False
6,Account,442,1,442.0,True,False
7,Transaction,852,2,426.0,True,False
8,Gas,420,1,420.0,True,False
9,Difficulty,387,1,387.0,True,False
10,Transactions,345,1,345.0,True,False
11,GasLimit,341,1,341.0,True,False
12,GasPrice,319,1,319.0,True,False
13,Storage,253,1,253.0,False,False
14,ChainID,246,1,246.0,False,False
15,GasUsed,219,1,219.0,False,False
16,Timestamp,188,1,188.0,False,False
17,AccessList,182,1,182.0,False,False
18,Call,169,1,169.0,False,False
19,Status,168,1,168.0,False,False
20,Index,156,1,156.0,False,False
21,Withdrawals,148,1,148.0,False,False
22,ExcessBlobGas,146,1,146.0,False,False
23,BlobGasUsed,131,1,131.0,False,False
24,Miner,105,1,105.0,False,False
25,Logs,164,2,82.0,False,False
26,MaxFeePerGas,82,1,82.0,False,False
27,ExtraData,73,1,73.0,False,False
28,MaxPriorityFeePerGas,72,1,72.0,False,False
29,Parent,60,1,60.0,False,False
30,Blocks,59,1,59.0,False,False
31,CumulativeGasUsed,51,1,51.0,False,False
32,StateRoot,51,1,51.0,False,False
33,Raw,47,1,47.0,False,False
34,BaseFeePerGas,32,1,32.0,False,False
35,LogsBloom,23,1,23.0,False,True
36,EffectiveGasPrice,23,1,23.0,False,True
37,TotalDifficulty,18,1,18.0,False,True
38,BlobGasPrice,17,1,17.0,False,True
39,EstimateGas,17,1,17.0,False,True
40,BlobVersionedHashes,17,1,17.0,False,True
41,Ommers,17,1,17.0,False,True
42,MixHash,16,1,16.0,False,True
43,ReceiptsRoot,16,1,16.0,False,True
44,WithdrawalsRoot,14,1,14.0,False,True
45,YParity,12,1,12.0,False,True
46,OmmerHash,12,1,12.0,False,True
47,TransactionCount,9,1,9.0,False,True
48,MaxFeePerBlobGas,8,1,8.0,False,True
49,TransactionsRoot,4,1,4.0,False,True
50,EffectiveTip,2,1,2.0,False,True
51,SendRawTransaction,4,2,2.0,False,True
52,NextBaseFeePerGas,2,1,2.0,False,True
53,OmmerCount,2,1,2.0,False,True
54,RawHeader,2,1,2.0,False,True
55,CreatedContract,2,1,2.0,False,True
56,OmmerAt,2,1,2.0,False,True
57,InputData,2,1,2.0,False,True

   Word  Count Search  Count Markup       Ratio
0  MEAN    303.206897      1.051724  294.413793

49.38383838383838

In [166]:
folder = 'e:\\phd\\test_repos_graphql2\\exo\\'
words = {
    "Components": 2,
    "FindManifest": 1,
    "WatchJob": 1,
    "StackByID": 1,
    "DestroyComponents": 1,
    "UpdateComponent": 2,
    "DestroyStack": 1,
    "FinishTask": 1,
    "AcquireTask": 1,
    "DisposeResource": 1,
    "UpdateResource": 2,
    "RestartWorkspaceComponents": 1,
    "CreateWorkspace": 2,
    "CreateProject": 1,
    "ResourceByID": 1,
    "MakeManifest": 1,
    "FindEntity": 1,
    "Stack": 1,
    "Manifest": 1,
    "BuildWorkspace": 1,
    "DestroyWorkspace": 1,
    "TaskByID": 1,
    "DisplayName": 1,
    "ForgetResource": 1,
    "ReconcileComponent": 1,
    "InitializeResource": 1,
    "RefreshResource": 1,
    "RefreshCluster": 1,
    "SetWorkspaceStack": 1,
    "Build": 1,
    "Project": 1,
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,Stack,85,1,85.0,True,False
1,DisplayName,75,1,75.0,True,False
2,Build,54,1,54.0,True,False
3,Components,75,2,37.5,True,False
4,Project,36,1,36.0,True,False
5,Manifest,26,1,26.0,True,True
6,CreateProject,5,1,5.0,True,True
7,CreateWorkspace,7,2,3.5,True,True
8,DestroyComponents,3,1,3.0,True,True
9,UpdateResource,6,2,3.0,True,True
10,DestroyWorkspace,2,1,2.0,True,True
11,UpdateComponent,4,2,2.0,True,True
12,RestartWorkspaceComponents,1,1,1.0,False,True
13,StackByID,1,1,1.0,False,True
14,WatchJob,1,1,1.0,False,True
15,SetWorkspaceStack,1,1,1.0,False,True
16,RefreshCluster,1,1,1.0,False,True
17,RefreshResource,1,1,1.0,False,True
18,InitializeResource,1,1,1.0,False,True
19,ReconcileComponent,1,1,1.0,False,True
20,ForgetResource,1,1,1.0,False,True
21,TaskByID,1,1,1.0,False,True
22,DisposeResource,1,1,1.0,False,True
23,FinishTask,1,1,1.0,False,True
24,BuildWorkspace,1,1,1.0,False,True
25,DestroyStack,1,1,1.0,False,True
26,AcquireTask,1,1,1.0,False,True
27,FindEntity,1,1,1.0,False,True
28,FindManifest,1,1,1.0,False,True
29,ResourceByID,1,1,1.0,False,True
30,MakeManifest,1,1,1.0,False,True

   Word  Count Search  Count Markup      Ratio
0  MEAN     12.806452      1.129032  11.322581

6.773809523809524

In [167]:
folder = 'e:\\phd\\test_repos_graphql2\\HydroAPI\\'
words = {
    "Merit": 1,
    "Strike": 1,
    "Giveaway": 1,
    "Server": 1,
    "User": 1,
    "Msgs": 1,
}
analyze(folder, words)

       Word  Count Search  Count Markup  Ratio  IsOutlier_MAD  ratio<30
0    Server           109             1  109.0          False     False
1      User            95             1   95.0          False     False
2  Giveaway            54             1   54.0          False     False
3     Merit            44             1   44.0          False     False
4    Strike            44             1   44.0          False     False
5      Msgs             7             1    7.0          False      True

   Word  Count Search  Count Markup      Ratio
0  MEAN     58.833333           1.0  58.833333

47.666666666666664

In [168]:
folder = 'e:\\phd\\test_repos_graphql2\\mattermost-plugin-playbooks\\'
words = {
    "UpdateRunTaskActions": 1,
    "ChangeRunOwner": 1,
    "RemoveRunParticipants": 1,
    "AddRunParticipants": 1,
    "UpdateRun": 1,
    "SetRunFavorite": 1,
    "RemovePlaybookMember": 2,
    "AddPlaybookMember": 2,
    "DeleteMetric": 2,
    "UpdateMetric": 2,
    "AddMetric": 2,
    "UpdatePlaybook": 2,
    "UpdatePlaybookFavorite": 1,
    "Runs": 1,
    "Run": 1,
    "Playbooks": 1,
    "Playbook": 1
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,Run,463,1,463.0,True,False
1,Playbook,353,1,353.0,True,False
2,Playbooks,180,1,180.0,True,False
3,Runs,55,1,55.0,True,False
4,UpdateRunTaskActions,7,1,7.0,True,True
5,UpdatePlaybook,12,2,6.0,True,True
6,ChangeRunOwner,4,1,4.0,False,True
7,UpdateRun,4,1,4.0,False,True
8,UpdateMetric,7,2,3.5,False,True
9,AddMetric,7,2,3.5,False,True
10,DeleteMetric,7,2,3.5,False,True
11,SetRunFavorite,3,1,3.0,False,True
12,UpdatePlaybookFavorite,3,1,3.0,False,True
13,AddRunParticipants,3,1,3.0,False,True
14,RemoveRunParticipants,3,1,3.0,False,True
15,RemovePlaybookMember,5,2,2.5,False,True
16,AddPlaybookMember,5,2,2.5,False,True

   Word  Count Search  Count Markup      Ratio
0  MEAN     65.941176      1.352941  64.676471

6.570776255707763

In [169]:
folder = 'e:\\phd\\test_repos_graphql2\\SlabAPI\\'
words = {
    "GetViewCount": 2,
    "GetView": 1,
    "GetAllViews": 1,
    "GetUser": 1,
    "GetTrigger": 1,
    "GetAllTriggers": 1,
    "GetAllTickets": 1,
    "GetOrganization": 1,
}
analyze(folder, words)

              Word  Count Search  Count Markup  Ratio  IsOutlier_MAD  ratio<30
0       GetTrigger            11             1   11.0          False      True
1  GetOrganization            11             1   11.0          False      True
2          GetView            10             1   10.0          False      True
3          GetUser            10             1   10.0          False      True
4   GetAllTriggers             7             1    7.0          False      True
5    GetAllTickets             7             1    7.0          False      True
6      GetAllViews             6             1    6.0          False      True
7     GetViewCount            10             2    5.0          False      True

   Word  Count Search  Count Markup  Ratio
0  MEAN           9.0         1.125  8.375

27.11111111111111

In [170]:
folder = 'e:\\phd\\test_repos_graphql2\\sturdy\\'
words = {
    "Integrations": 1,
    "UpdatedGitHubPullRequestStatuses": 1,
    "PullCodebase": 1,
    "CreateOrUpdateCodebaseRemote": 1,
    "UpdateInstallation": 1,
    "DeleteIntegration": 1,
    "SetupGitHubRepository": 1,
    "Activity": 1,
    "DownloadZip": 1,
    "Changes": 1,
    "Members": 2,
    "LastUsedView": 2,
    "UpdatedOrganization": 1,
    "UpdatedSuggestion": 1,
    "UpdatedView": 1,
    "UpdatedWorkspaceDiffs": 1,
    "GenerateKeyPair": 1,
    "RemovePatches": 2,
    "DismissSuggestionHunks": 1,
    "AddPublicKey": 1,
    "WatchWorkspace": 1,
    "RequestReview": 1,
    "UpdateACL": 1,
    "ArchiveNotifications": 1,
    "AddUserToCodebase": 1,
    "VerifyEmail": 2,
    "UpdateUser": 2,
    "DeleteComment": 1,
    "LandWorkspaceChange": 2,
    "Comment": 3,
    "Workspaces": 2,
    "ResolvedBy": 1,
    "Notifications": 1,
    "UpdateComment": 1,
    "CreateComment": 1,
    "UpdateCodebase": 1,
    "ReportWorkspacePresence": 1,
    "DismissSuggestion": 1,
    "UpdateOrganization": 1,
    "UpdatedWorkspacesStatuses": 1,
    "CreateOrUpdateGitHubPullRequest": 1,
    "TriggerInstantIntegration": 1,
    "PushCodebase": 1,
    "UpdatedGitHubPullRequest": 1,
}
analyze(folder, words)

,Word,Count Search,Count Markup,Ratio,IsOutlier_MAD,ratio<30
0,Activity,43,1,43.000000,True,False
1,Comment,94,3,31.333333,True,False
2,LandWorkspaceChange,22,2,11.000000,True,True
3,Members,19,2,9.500000,True,True
4,AddPublicKey,7,1,7.000000,True,True
5,ResolvedBy,6,1,6.000000,True,True
6,Changes,6,1,6.000000,True,True
7,UpdateInstallation,4,1,4.000000,True,True
8,DownloadZip,4,1,4.000000,True,True
9,CreateOrUpdateGitHubPullRequest,4,1,4.000000,True,True
10,CreateComment,4,1,4.000000,True,True
11,RemovePatches,7,2,3.500000,True,True
12,VerifyEmail,7,2,3.500000,True,True
13,UpdatedGitHubPullRequestStatuses,3,1,3.000000,True,True
14,UpdatedGitHubPullRequest,3,1,3.000000,True,True
15,SetupGitHubRepository,3,1,3.000000,True,True
16,CreateOrUpdateCodebaseRemote,3,1,3.000000,True,True
17,ReportWorkspacePresence,2,1,2.000000,False,True
18,UpdateCodebase,2,1,2.000000,False,True
19,DismissSuggestion,2,1,2.000000,False,True
20,UpdatedWorkspacesStatuses,2,1,2.000000,False,True
21,UpdateComment,2,1,2.000000,False,True
22,Notifications,2,1,2.000000,False,True
23,TriggerInstantIntegration,2,1,2.000000,False,True
24,Workspaces,4,2,2.000000,False,True
25,PushCodebase,2,1,2.000000,False,True
26,UpdateOrganization,2,1,2.000000,False,True
27,Integrations,2,1,2.000000,False,True
28,DeleteComment,2,1,2.000000,False,True
29,UpdateUser,4,2,2.000000,False,True
30,AddUserToCodebase,2,1,2.000000,False,True
31,ArchiveNotifications,2,1,2.000000,False,True
32,RequestReview,2,1,2.000000,False,True
33,WatchWorkspace,2,1,2.000000,False,True
34,DismissSuggestionHunks,2,1,2.000000,False,True
35,GenerateKeyPair,2,1,2.000000,False,True
36,UpdatedWorkspaceDiffs,2,1,2.000000,False,True
37,UpdatedView,2,1,2.000000,False,True
38,UpdatedSuggestion,2,1,2.000000,False,True
39,UpdatedOrganization,2,1,2.000000,False,True
40,LastUsedView,4,2,2.000000,False,True
41,DeleteIntegration,2,1,2.000000,False,True
42,PullCodebase,2,1,2.000000,False,True
43,UpdateACL,2,1,2.000000,False,True

   Word  Count Search  Count Markup     Ratio
0  MEAN      6.795455      1.204545  4.609848

10.017857142857142

In [171]:
folder = 'e:\\phd\\test_repos_graphql2\\toolkit-for-cardano\\'
words = {
    "WalletDelegate": 1,
    "WalletRegister": 1,
    "WalletFund": 1,
    "WalletCreate": 1,
    "SendFunds": 1,
    "TxSubmit": 1,
    "TxSign": 1,
    "TxBuild": 1,
    "Mint": 1,
    "Wallets": 1,
    "Utxos": 2,
    "TxFee": 1,
}
analyze(folder, words)

              Word  Count Search  Count Markup  Ratio  IsOutlier_MAD  ratio<30
0            Utxos            22             2   11.0           True      True
1             Mint             9             1    9.0           True      True
2   WalletDelegate             2             1    2.0          False      True
3   WalletRegister             2             1    2.0          False      True
4         TxSubmit             2             1    2.0          False      True
5           TxSign             2             1    2.0          False      True
6            TxFee             2             1    2.0          False      True
7       WalletFund             1             1    1.0          False      True
8     WalletCreate             1             1    1.0          False      True
9        SendFunds             1             1    1.0          False      True
10         TxBuild             1             1    1.0          False      True
11         Wallets             1             1    1.0          False      True

   Word  Count Search  Count Markup     Ratio
0  MEAN      3.833333      1.083333  2.916667

12.969696969696969

In [135]:
data = global_array
# Определяем границы интервалов
bins = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30, 50, 100, 7000]

# Задаем названия интервалов
intervals = [
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
    '11-15', '16-20', '21-30', '31-50', '51-100', '>100'
]

# Считаем количество элементов в каждом интервале
counts, _ = np.histogram(data, bins=bins)

# Создаем словарь {интервал: количество}
result = dict(zip(intervals, counts))
print(result)

{'1': 56, '2': 50, '3': 22, '4': 20, '5': 7, '6': 7, '7': 13, '8': 13, '9': 11, '10': 24, '11-15': 8, '16-20': 12, '21-30': 17, '31-50': 22, '51-100': 43, '>100': 0}

In [150]:
print(len(data[data==1]))
print(len(data[(data>1)&(data<=4)]))
print(len(data[(data>5)&(data<=10)]))
print(len(data[(data>10)]))

56
91
51
119

In [109]:
# folder = 'e:\\phd\\test_repos\\modules\\'
# words = {
#     "CompleteFollowup": 1, 
#     "ReAssignFollowup": 2,
#     "RemovePharmacy": 1,
#     "SetABVariant": 1,
#     "BlockPatient": 1,
#     "SetMediaRead": 1,
#     "ValidateAppointmentInsurance": 3,
#     "UpdateProviderInsurance": 1,
#     "EditStateCompanies": 1,
#     "UpdateEncounterScreenedStatus": 1,
#     "StartPaymentTransaction": 1,
#     "SubscribeToPhoneCallEvents": 1,
#     "SetAppointmentType": 1,
#     "MakeCardDefault": 2,
#     "DeletePatientNote": 1,
#     "UpdatePatientNote": 1,
#     "SetVisitTypeOrders": 2,
#     "SetVisitTypeVisibility": 2,
#     "AddICD10MedicalCode": 2,
#     "AddMedicalCodes": 1,
#     "InviteClient": 1,
#     "DeleteEvent": 1,
#     "NeedFollowup": 1,
#     "TwilioInfo": 1,
#     "CurrentTime": 1,
#     "Person": 1,
#     "PHIData": 1,
#     "Clients": 1,
#     "Messages": 1,
#     "PastVisits": 1,
#     "Appointment": 1,
#     "CheckInData": 1,
#     "NoteTemplate": 1,
#     "VisitType": 1,
#     "ScheduleVisit": 1,
#     "UpdateAvailability": 1,
#     "AssignQuestionnaire": 1,
#     "PublishForm": 1,
#     "LoadFollowupByPatients": 1,
#     "InsuranceCosts": 1,
#     "PatientDetails": 1,
#     "ConsentForms": 1
# }
# analyze(folder, words)

In [95]:
# folder = 'e:\\phd\\test_repos_graphql2\\bramble\\'
# words = {
#     "UploadGadgetFile": 1, 
#     "UploadGizmoFile": 1, 
#     "Gizmo": 2, 
#     "Gizmos": 2, 
#     "Delay": 1, 
#     "Gizmos": 2, 
#     "RandomGizmo": 1,
# }
# analyze(folder, words)

In [110]:
# folder = 'e:\\phd\\test_repos_graphql2\\go-graphql-starter\\'
# words = {
#     "Signup": 1,
#     "User": 1,
#     "Login": 1,
#     "Viewer": 1,
# }
# analyze(folder, words)

In [105]:
# folder = 'e:\\phd\\test_repos\\backend\\fsm-gateway\\'
# words = {
#     "GetSession": 1, 
#     "GetDocumentData": 1,
#     "GetDocumentText": 1,
#     "GetConsentList": 1,
#     "StartSession": 1,
#     "SendDocumentData": 1,
#     "FinishSession": 1,
#     "StartAuthSessionByPhone": 1,
#     "GetJwtByPhoneCode": 1,
#     "GetJwtByRefreshToken": 1
# }
# df = analyze(folder, words)

In [106]:
# folder = 'e:\\phd\\test_repos\\LP\\delivery-offering\\'
# words = {
#     "DeliveryTimeslots": 2, 
#     "DeliveryTimeslot": 2, 
#     "DeliveryTypes": 2, 
#     "ReserveDeliveryTimeslot": 2,
#     "LookupDeliveryOffers": 2,
#     "DeliveryOfferByID": 2,
#     "AcceptDeliveryOffer": 2,
#     "ValidateDeliveryOffer": 2,
# }
# analyze(folder, words)

In [107]:
# folder = 'e:\\phd\\test_repos\\LP\\warehouses\\'
# words = {
#     "TerminateWarehouses": 2, 
#     "UpdateWarehouses": 2, 
#     "CreateWarehouses": 2, 
#     "Warehouses": 2,
# }
# analyze(folder, words)

In [108]:
# folder = 'e:\\phd\\test_repos\\LP\\channel-profile\\'
# words = {
#     "CreateChannelProfile": 2, 
#     "UpdateChannelProfile": 2, 
#     "DeleteChannelProfile": 2, 
#     "ChannelProfiles": 2,
#     "ChannelsByFilter": 2,
# }
# analyze(folder, words)