In [116]:
import os
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [95]:
def count_words_in_go_files(folder_path, words_dict):
    word_search_counts = {word: 0 for word in words_dict.keys()}
    word_markup_counts = words_dict.copy()
    
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, words_dict.keys())) + r')\b')
    
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith('.go'):
                file_path = os.path.join(root, file)
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        matches = pattern.findall(content)
                        for word in matches:
                            word_search_counts[word] += 1
                except (UnicodeDecodeError, PermissionError) as e:
                    print(f"Ошибка при обработке файла {file_path}: {e}")
    
    # Создаем DataFrame
    df = pd.DataFrame({
        'Word': list(word_search_counts.keys()),
        'Count Search': list(word_search_counts.values()),
        'Count Markup': [word_markup_counts[word] for word in word_search_counts.keys()]
    })
    
    # Вычисляем Ratio
    df['Ratio'] = df['Count Search'] / df['Count Markup']
    
    # Сортируем по Ratio (по убыванию)
    df_sorted = df.sort_values(by='Ratio', ascending=False)
    df_sorted.reset_index(drop=True, inplace=True)
    
    return df_sorted

In [96]:
global_array = np.array([])

In [97]:
def analyze(folder, words):
    result_df = count_words_in_go_files(folder, words)

    mean_row = pd.DataFrame({
        'Word': ['MEAN'],
        'Count Search': [result_df['Count Search'].mean()],
        'Count Markup': [result_df['Count Markup'].mean()],
        'Ratio': [result_df['Ratio'].mean()]
    })
    
    global global_array
    global_array = np.append(global_array, result_df['Ratio'].values)

    display(result_df)
    display(mean_row)

In [98]:
folder = 'e:\\phd\\test_repos\\backend\\fsm-gateway\\'
words = {
    "GetOrderById": 1, 
    "GetSession": 1, 
    "GetDocumentData": 1,
    "GetDocumentText": 1,
    "GetConsentList": 1,
    "StartSession": 1,
    "SendDocumentData": 1,
    "FinishSession": 1,
    "Logout": 1,
    "StartAuthSessionByPhone": 1,
    "GetJwtByPhoneCode": 1,
    "GetJwtByRefreshToken": 1
}
analyze(folder, words)

                       Word  Count Search  Count Markup  Ratio
0      GetJwtByRefreshToken            25             1   25.0
1   StartAuthSessionByPhone            21             1   21.0
2         GetJwtByPhoneCode            21             1   21.0
3                GetSession            11             1   11.0
4           GetDocumentData            10             1   10.0
5              StartSession            10             1   10.0
6           GetDocumentText             9             1    9.0
7            GetConsentList             9             1    9.0
8          SendDocumentData             9             1    9.0
9             FinishSession             9             1    9.0
10             GetOrderById             4             1    4.0
11                   Logout             1             1    1.0

   Word  Count Search  Count Markup      Ratio
0  MEAN     11.583333           1.0  11.583333

In [99]:
folder = 'e:\\phd\\test_repos\\LP\\delivery-offering\\'
words = {
    "DeliveryTimeslots": 2, 
    "DeliveryTimeslot": 2, 
    "DeliveryTypes": 2, 
    "ReserveDeliveryTimeslot": 2,
    "LookupDeliveryOffers": 2,
    "DeliveryOfferByID": 2,
    "AcceptDeliveryOffer": 2,
    "ValidateDeliveryOffer": 2,
}
analyze(folder, words)

                      Word  Count Search  Count Markup  Ratio
0         DeliveryTimeslot            94             2   47.0
1            DeliveryTypes            29             2   14.5
2     LookupDeliveryOffers            22             2   11.0
3      AcceptDeliveryOffer            19             2    9.5
4        DeliveryOfferByID            17             2    8.5
5  ReserveDeliveryTimeslot            16             2    8.0
6        DeliveryTimeslots            12             2    6.0
7    ValidateDeliveryOffer            12             2    6.0

   Word  Count Search  Count Markup    Ratio
0  MEAN        27.625           2.0  13.8125

In [100]:
folder = 'e:\\phd\\test_repos\\LP\\warehouses\\'
words = {
    "TerminateWarehouses": 2, 
    "UpdateWarehouses": 2, 
    "CreateWarehouses": 2, 
    "Warehouses": 2,
}
analyze(folder, words)

                  Word  Count Search  Count Markup  Ratio
0           Warehouses            71             2   35.5
1     UpdateWarehouses            23             2   11.5
2     CreateWarehouses            22             2   11.0
3  TerminateWarehouses            20             2   10.0

   Word  Count Search  Count Markup  Ratio
0  MEAN          34.0           2.0   17.0

In [101]:
folder = 'e:\\phd\\test_repos\\LP\\channel-profile\\'
words = {
    "CreateChannelProfile": 2, 
    "UpdateChannelProfile": 2, 
    "DeleteChannelProfile": 2, 
    "ChannelProfiles": 2,
    "ChannelsByFilter": 2,
}
analyze(folder, words)

                   Word  Count Search  Count Markup  Ratio
0      ChannelsByFilter            17             2    8.5
1  CreateChannelProfile            16             2    8.0
2  UpdateChannelProfile            16             2    8.0
3  DeleteChannelProfile            16             2    8.0
4       ChannelProfiles            15             2    7.5

   Word  Count Search  Count Markup  Ratio
0  MEAN          16.0           2.0    8.0

In [102]:
folder = 'e:\\phd\\test_repos\\modules\\'
words = {
    "CompleteFollowup": 1, 
    "ReAssignFollowup": 2,
    "RemovePharmacy": 1,
    "SetABVariant": 1,
    "BlockPatient": 1,
    "SetMediaRead": 1,
    "ValidateAppointmentInsurance": 3,
    "UpdateProviderInsurance": 1,
    "EditStateCompanies": 1,
    "UpdateEncounterScreenedStatus": 1,
    "StartPaymentTransaction": 1,
    "SubscribeToPhoneCallEvents": 1,
    "SetAppointmentType": 1,
    "MakeCardDefault": 2,
    "DeletePatientNote": 1,
    "UpdatePatientNote": 1,
    "SetVisitTypeOrders": 2,
    "SetVisitTypeVisibility": 2,
    "AddICD10MedicalCode": 2,
    "AddMedicalCodes": 1,
    "InviteClient": 1,
    "DeleteEvent": 1,
    "NeedFollowup": 1,
    "TwilioInfo": 1,
    "CurrentTime": 1,
    "Person": 1,
    "PHIData": 1,
    "Clients": 1,
    "Messages": 1,
    "PastVisits": 1,
    "Appointment": 1,
    "CheckInData": 1,
    "NoteTemplate": 1,
    "VisitType": 1,
    "ScheduleVisit": 1,
    "UpdateAvailability": 1,
    "AssignQuestionnaire": 1,
    "PublishForm": 1,
    "LoadFollowupByPatients": 1,
    "InsuranceCosts": 1,
    "PatientDetails": 1,
    "ConsentForms": 1
}
analyze(folder, words)

                             Word  Count Search  Count Markup       Ratio
0                     Appointment           219             1  219.000000
1                       VisitType           123             1  123.000000
2                          Person           111             1  111.000000
3                        Messages            35             1   35.000000
4                         PHIData            27             1   27.000000
5                    NoteTemplate            26             1   26.000000
6                     CheckInData            12             1   12.000000
7                  PatientDetails            11             1   11.000000
8                      TwilioInfo             8             1    8.000000
9               DeletePatientNote             7             1    7.000000
10        StartPaymentTransaction             7             1    7.000000
11              UpdatePatientNote             7             1    7.000000
12                    CurrentTime             6             1    6.000000
13             UpdateAvailability             5             1    5.000000
14                   NeedFollowup             5             1    5.000000
15                        Clients             5             1    5.000000
16             SetAppointmentType             5             1    5.000000
17                MakeCardDefault             9             2    4.500000
18            AddICD10MedicalCode             8             2    4.000000
19                 RemovePharmacy             4             1    4.000000
20                   BlockPatient             4             1    4.000000
21     SubscribeToPhoneCallEvents             4             1    4.000000
22             EditStateCompanies             4             1    4.000000
23        UpdateProviderInsurance             4             1    4.000000
24                   SetABVariant             4             1    4.000000
25   ValidateAppointmentInsurance            11             3    3.666667
26         SetVisitTypeVisibility             7             2    3.500000
27               ReAssignFollowup             7             2    3.500000
28             SetVisitTypeOrders             7             2    3.500000
29                    PublishForm             2             1    2.000000
30            AssignQuestionnaire             2             1    2.000000
31         LoadFollowupByPatients             1             1    1.000000
32                 InsuranceCosts             1             1    1.000000
33               CompleteFollowup             1             1    1.000000
34                    DeleteEvent             1             1    1.000000
35                  ScheduleVisit             1             1    1.000000
36                     PastVisits             1             1    1.000000
37                   InviteClient             1             1    1.000000
38                AddMedicalCodes             1             1    1.000000
39  UpdateEncounterScreenedStatus             1             1    1.000000
40                   SetMediaRead             1             1    1.000000
41                   ConsentForms             1             1    1.000000

   Word  Count Search  Count Markup      Ratio
0  MEAN     16.833333      1.166667  16.206349

In [103]:
folder = 'e:\\phd\\test_repos_graphql2\\boost\\'
words = {
    "DealUpdate": 1, 
    "StorageAskUpdate": 1, 
    "FundsMoveToEscrow": 1, 
    "DealFailPaused": 1, 
    "DealRetryPaused": 1, 
    "DealCancel": 1, 
    "Mpool": 1, 
    "FundsLogs": 1, 
    "ProposalLogs": 1, 
    "LegacyDeals": 1, 
    "Deals": 1, 
    "LegacyDeal": 1, 
    "Deal": 2, 
    "DealNew": 1, 
    "DealsCount": 1, 
    "StorageAsk": 1, 
    "DealPublishNow": 1, 
    "DealPublish": 1,
    "Epoch": 1,
    "Funds": 1,
    "ProposalLogsCount": 1,
    "SealingPipeline": 1,
    "Storage": 1,
    "Transfers": 1,
    
}
analyze(folder, words)

                 Word  Count Search  Count Markup  Ratio
0               Deals            56             1   56.0
1          StorageAsk            32             1   32.0
2             Storage            26             1   26.0
3                Deal            16             2    8.0
4               Epoch             7             1    7.0
5        ProposalLogs             5             1    5.0
6           FundsLogs             4             1    4.0
7           Transfers             4             1    4.0
8             DealNew             2             1    2.0
9         DealPublish             2             1    2.0
10              Funds             2             1    2.0
11    SealingPipeline             2             1    2.0
12              Mpool             1             1    1.0
13        LegacyDeals             1             1    1.0
14         DealCancel             1             1    1.0
15         LegacyDeal             1             1    1.0
16   StorageAskUpdate             1             1    1.0
17         DealsCount             1             1    1.0
18    DealRetryPaused             1             1    1.0
19     DealPublishNow             1             1    1.0
20     DealFailPaused             1             1    1.0
21  ProposalLogsCount             1             1    1.0
22  FundsMoveToEscrow             1             1    1.0
23         DealUpdate             1             1    1.0

   Word  Count Search  Count Markup  Ratio
0  MEAN      7.083333      1.041667   6.75

In [104]:
folder = 'e:\\phd\\test_repos_graphql2\\bramble\\'
words = {
    "UploadGadgetFile": 1, 
    "UploadGizmoFile": 1, 
    "Gizmo": 2, 
    "Gizmos": 2, 
    "Delay": 1, 
    "Gizmos": 2, 
    "RandomGizmo": 1,
}
analyze(folder, words)

               Word  Count Search  Count Markup  Ratio
0             Gizmo           297             2  148.5
1  UploadGadgetFile             1             1    1.0
2   UploadGizmoFile             1             1    1.0
3            Gizmos             2             2    1.0
4             Delay             1             1    1.0
5       RandomGizmo             1             1    1.0

   Word  Count Search  Count Markup      Ratio
0  MEAN          50.5      1.333333  25.583333

In [105]:
folder = 'e:\\phd\\test_repos_graphql2\\circuit\\'
words = {
    "Secrets": 2, 
    "Services": 2, 
    "Releases": 2, 
    "EnvsDeployedIn": 2, 
    "Features": 2, 
    "GetGitCommits": 1, 
    "BookmarkProject": 1, 
    "UpdateProjectEnvironments": 1, 
    "UpdateUserPermissions": 1, 
    "DeleteProjectExtension": 1, 
    "UpdateProjectExtension": 1, 
    "CreateProjectExtension": 1, 
    "DeleteExtension": 1, 
    "UpdateExtension": 1, 
    "CreateExtension": 1, 
    "ImportSecrets": 1, 
    "DeleteSecret": 1, 
    "UpdateSecret": 1, 
    "CreateSecret": 1, 
    "DeleteEnvironment": 1,
    "UpdateEnvironment": 1, 
    "CreateEnvironment": 1, 
    "DeleteServiceSpec": 1, 
    "UpdateServiceSpec": 1, 
    "CreateServiceSpec": 1, 
    "ImportServices": 1, 
    "DeleteService": 1, 
    "UpdateService": 1, 
    "CreateService": 1, 
    "StopRelease": 1,
    "CreateRelease": 1, 
    "UpdateProject": 1, 
    "CreateProject": 1, 
    "Permissions": 1, 
    "ReleaseExtensions": 1, 
    "ProjectExtensions": 1, 
    "Extensions": 1, 
    "Secret": 1, 
    "ExportSecrets": 1, 
    "Environments": 1, 
    "ServiceSpecs": 1, 
    "Users": 1, 
    "User": 1, 
    "Bookmarked": 1, 
}
analyze(folder, words)

                         Word  Count Search  Count Markup   Ratio
0                        User          2577             1  2577.0
1                      Secret           660             1   660.0
2                  Extensions           379             1   379.0
3                 Permissions           371             1   371.0
4                    Services           541             2   270.5
5               CreateProject           180             1   180.0
6           CreateEnvironment           164             1   164.0
7                     Secrets           299             2   149.5
8               CreateService           143             1   143.0
9                       Users           122             1   122.0
10               CreateSecret            99             1    99.0
11              UpdateService            82             1    82.0
12              UpdateProject            66             1    66.0
13            CreateExtension            61             1    61.0
14          CreateServiceSpec            55             1    55.0
15               UpdateSecret            54             1    54.0
16     CreateProjectExtension            54             1    54.0
17          UpdateEnvironment            41             1    41.0
18              DeleteService            39             1    39.0
19              CreateRelease            37             1    37.0
20               Environments            33             1    33.0
21                   Features            62             2    31.0
22               DeleteSecret            27             1    27.0
23          ProjectExtensions            26             1    26.0
24          DeleteEnvironment            21             1    21.0
25                 Bookmarked            17             1    17.0
26             ImportServices            12             1    12.0
27          ReleaseExtensions            12             1    12.0
28                StopRelease            12             1    12.0
29              ImportSecrets            10             1    10.0
30  UpdateProjectEnvironments            10             1    10.0
31                   Releases            19             2     9.5
32      UpdateUserPermissions             9             1     9.0
33          DeleteServiceSpec             9             1     9.0
34     DeleteProjectExtension             8             1     8.0
35     UpdateProjectExtension             8             1     8.0
36          UpdateServiceSpec             8             1     8.0
37            BookmarkProject             8             1     8.0
38            DeleteExtension             7             1     7.0
39              ExportSecrets             7             1     7.0
40            UpdateExtension             7             1     7.0
41               ServiceSpecs             4             1     4.0
42             EnvsDeployedIn             8             2     4.0
43              GetGitCommits             3             1     3.0

   Word  Count Search  Count Markup       Ratio
0  MEAN    144.795455      1.113636  134.238636

In [106]:
folder = 'e:\\phd\\test_repos_graphql2\\core-geth\\'
words = {
    "SendRawTransaction": 2,
    "Logs": 2,
    "Transaction": 2,
    "Blocks": 1,
    "Block": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "OmmerAt": 1,
    "Miner": 1,
    "CreatedContract": 1,
    "Account": 1,
    "Storage": 1,
    "Status": 1,
    "Nonce": 1,
    "Hash": 1,
    "TransactionCount": 1,
    "ChainID": 1,
    "MaxPriorityFeePerGas": 1,
    "GasPrice": 1,
    "Transactions": 1,
    "ExcessBlobGas": 1,
    "BlobGasUsed": 1,
    "Withdrawals": 1,
    "WithdrawalsRoot": 1,
    "Raw": 1,
    "RawHeader": 1,
    "TotalDifficulty": 1,
    "LogsBloom": 1,
    "ExtraData": 1,
    "Ommers": 1,
    "OmmerCount": 1,
    "OmmerHash": 1,
    "ReceiptsRoot": 1,
    "StateRoot": 1,
    "TransactionsRoot": 1,
    "MixHash": 1,
    "Timestamp": 1,
    "Difficulty": 1,
    "Parent": 1,
    "NextBaseFeePerGas": 1,
    "BaseFeePerGas": 1,
    "GasUsed": 1,
    "GasLimit": 1,
    "Number": 1,
    "YParity": 1,
    "AccessList": 1,
    "Type": 1,
    "BlobGasPrice": 1,
    "CumulativeGasUsed": 1,
    "Index": 1,
    "Value": 1,
    "EffectiveTip": 1,
    "BlobVersionedHashes": 1,
    "MaxFeePerBlobGas": 1,
    "MaxFeePerGas": 1,
    "EffectiveGasPrice": 1,
    "Gas": 1,
    "InputData": 1
}
analyze(folder, words)

                    Word  Count Search  Count Markup   Ratio
0                   Hash          6364             1  6364.0
1                 Number          1446             1  1446.0
2                  Value          1096             1  1096.0
3                   Type          1049             1  1049.0
4                  Block           770             1   770.0
5                  Nonce           712             1   712.0
6                Account           442             1   442.0
7            Transaction           852             2   426.0
8                    Gas           420             1   420.0
9             Difficulty           387             1   387.0
10          Transactions           345             1   345.0
11              GasLimit           341             1   341.0
12              GasPrice           319             1   319.0
13               Storage           253             1   253.0
14               ChainID           246             1   246.0
15               GasUsed           219             1   219.0
16             Timestamp           188             1   188.0
17            AccessList           182             1   182.0
18                  Call           169             1   169.0
19                Status           168             1   168.0
20                 Index           156             1   156.0
21           Withdrawals           148             1   148.0
22         ExcessBlobGas           146             1   146.0
23           BlobGasUsed           131             1   131.0
24                 Miner           105             1   105.0
25                  Logs           164             2    82.0
26          MaxFeePerGas            82             1    82.0
27             ExtraData            73             1    73.0
28  MaxPriorityFeePerGas            72             1    72.0
29                Parent            60             1    60.0
30                Blocks            59             1    59.0
31     CumulativeGasUsed            51             1    51.0
32             StateRoot            51             1    51.0
33                   Raw            47             1    47.0
34         BaseFeePerGas            32             1    32.0
35             LogsBloom            23             1    23.0
36     EffectiveGasPrice            23             1    23.0
37       TotalDifficulty            18             1    18.0
38          BlobGasPrice            17             1    17.0
39           EstimateGas            17             1    17.0
40   BlobVersionedHashes            17             1    17.0
41                Ommers            17             1    17.0
42               MixHash            16             1    16.0
43          ReceiptsRoot            16             1    16.0
44       WithdrawalsRoot            14             1    14.0
45               YParity            12             1    12.0
46             OmmerHash            12             1    12.0
47      TransactionCount             9             1     9.0
48      MaxFeePerBlobGas             8             1     8.0
49      TransactionsRoot             4             1     4.0
50          EffectiveTip             2             1     2.0
51    SendRawTransaction             4             2     2.0
52     NextBaseFeePerGas             2             1     2.0
53            OmmerCount             2             1     2.0
54             RawHeader             2             1     2.0
55       CreatedContract             2             1     2.0
56               OmmerAt             2             1     2.0
57             InputData             2             1     2.0

   Word  Count Search  Count Markup       Ratio
0  MEAN    303.206897      1.051724  294.413793

In [107]:
folder = 'e:\\phd\\test_repos_graphql2\\exo\\'
words = {
    "Components": 2,
    "FindManifest": 1,
    "WatchJob": 1,
    "StackByID": 1,
    "DestroyComponents": 1,
    "UpdateComponent": 2,
    "DestroyStack": 1,
    "FinishTask": 1,
    "AcquireTask": 1,
    "DisposeResource": 1,
    "UpdateResource": 2,
    "RestartWorkspaceComponents": 1,
    "CreateWorkspace": 2,
    "CreateProject": 1,
    "ResourceByID": 1,
    "MakeManifest": 1,
    "FindEntity": 1,
    "Stack": 1,
    "Manifest": 1,
    "BuildWorkspace": 1,
    "DestroyWorkspace": 1,
    "TaskByID": 1,
    "DisplayName": 1,
    "ForgetResource": 1,
    "ReconcileComponent": 1,
    "InitializeResource": 1,
    "RefreshResource": 1,
    "RefreshCluster": 1,
    "SetWorkspaceStack": 1,
    "Build": 1,
    "Project": 1,
}
analyze(folder, words)

                          Word  Count Search  Count Markup  Ratio
0                        Stack            85             1   85.0
1                  DisplayName            75             1   75.0
2                        Build            54             1   54.0
3                   Components            75             2   37.5
4                      Project            36             1   36.0
5                     Manifest            26             1   26.0
6                CreateProject             5             1    5.0
7              CreateWorkspace             7             2    3.5
8            DestroyComponents             3             1    3.0
9               UpdateResource             6             2    3.0
10            DestroyWorkspace             2             1    2.0
11             UpdateComponent             4             2    2.0
12  RestartWorkspaceComponents             1             1    1.0
13                   StackByID             1             1    1.0
14                    WatchJob             1             1    1.0
15           SetWorkspaceStack             1             1    1.0
16              RefreshCluster             1             1    1.0
17             RefreshResource             1             1    1.0
18          InitializeResource             1             1    1.0
19          ReconcileComponent             1             1    1.0
20              ForgetResource             1             1    1.0
21                    TaskByID             1             1    1.0
22             DisposeResource             1             1    1.0
23                  FinishTask             1             1    1.0
24              BuildWorkspace             1             1    1.0
25                DestroyStack             1             1    1.0
26                 AcquireTask             1             1    1.0
27                  FindEntity             1             1    1.0
28                FindManifest             1             1    1.0
29                ResourceByID             1             1    1.0
30                MakeManifest             1             1    1.0

   Word  Count Search  Count Markup      Ratio
0  MEAN     12.806452      1.129032  11.322581

In [108]:
folder = 'e:\\phd\\test_repos_graphql2\\go-graphql-starter\\'
words = {
    "Signup": 1,
    "User": 1,
    "Login": 1,
    "Viewer": 1,
}
analyze(folder, words)

     Word  Count Search  Count Markup  Ratio
0    User             3             1    3.0
1  Signup             1             1    1.0
2   Login             1             1    1.0
3  Viewer             1             1    1.0

   Word  Count Search  Count Markup  Ratio
0  MEAN           1.5           1.0    1.5

In [109]:
folder = 'e:\\phd\\test_repos_graphql2\\HydroAPI\\'
words = {
    "Merit": 1,
    "Strike": 1,
    "Giveaway": 1,
    "Server": 1,
    "User": 1,
    "Msgs": 1,
}
analyze(folder, words)

       Word  Count Search  Count Markup  Ratio
0    Server           109             1  109.0
1      User            95             1   95.0
2  Giveaway            54             1   54.0
3     Merit            44             1   44.0
4    Strike            44             1   44.0
5      Msgs             7             1    7.0

   Word  Count Search  Count Markup      Ratio
0  MEAN     58.833333           1.0  58.833333

In [110]:
folder = 'e:\\phd\\test_repos_graphql2\\mattermost-plugin-playbooks\\'
words = {
    "UpdateRunTaskActions": 1,
    "ChangeRunOwner": 1,
    "RemoveRunParticipants": 1,
    "AddRunParticipants": 1,
    "UpdateRun": 1,
    "SetRunFavorite": 1,
    "RemovePlaybookMember": 2,
    "AddPlaybookMember": 2,
    "DeleteMetric": 2,
    "UpdateMetric": 2,
    "AddMetric": 2,
    "UpdatePlaybook": 2,
    "UpdatePlaybookFavorite": 1,
    "Runs": 1,
    "Run": 1,
    "Playbooks": 1,
    "Playbook": 1
}
analyze(folder, words)

                      Word  Count Search  Count Markup  Ratio
0                      Run           463             1  463.0
1                 Playbook           353             1  353.0
2                Playbooks           180             1  180.0
3                     Runs            55             1   55.0
4     UpdateRunTaskActions             7             1    7.0
5           UpdatePlaybook            12             2    6.0
6           ChangeRunOwner             4             1    4.0
7                UpdateRun             4             1    4.0
8             UpdateMetric             7             2    3.5
9                AddMetric             7             2    3.5
10            DeleteMetric             7             2    3.5
11          SetRunFavorite             3             1    3.0
12  UpdatePlaybookFavorite             3             1    3.0
13      AddRunParticipants             3             1    3.0
14   RemoveRunParticipants             3             1    3.0
15    RemovePlaybookMember             5             2    2.5
16       AddPlaybookMember             5             2    2.5

   Word  Count Search  Count Markup      Ratio
0  MEAN     65.941176      1.352941  64.676471

In [111]:
folder = 'e:\\phd\\test_repos_graphql2\\SlabAPI\\'
words = {
    "GetViewCount": 2,
    "GetView": 1,
    "GetAllViews": 1,
    "GetUser": 1,
    "GetTrigger": 1,
    "GetAllTriggers": 1,
    "GetAllTickets": 1,
    "GetOrganization": 1,
}
analyze(folder, words)

              Word  Count Search  Count Markup  Ratio
0       GetTrigger            11             1   11.0
1  GetOrganization            11             1   11.0
2          GetView            10             1   10.0
3          GetUser            10             1   10.0
4   GetAllTriggers             7             1    7.0
5    GetAllTickets             7             1    7.0
6      GetAllViews             6             1    6.0
7     GetViewCount            10             2    5.0

   Word  Count Search  Count Markup  Ratio
0  MEAN           9.0         1.125  8.375

In [112]:
folder = 'e:\\phd\\test_repos_graphql2\\sturdy\\'
words = {
    "Integrations": 1,
    "UpdatedGitHubPullRequestStatuses": 1,
    "PullCodebase": 1,
    "CreateOrUpdateCodebaseRemote": 1,
    "UpdateInstallation": 1,
    "DeleteIntegration": 1,
    "SetupGitHubRepository": 1,
    "Activity": 1,
    "DownloadZip": 1,
    "Changes": 1,
    "Members": 2,
    "LastUsedView": 2,
    "UpdatedOrganization": 1,
    "UpdatedSuggestion": 1,
    "UpdatedView": 1,
    "UpdatedWorkspaceDiffs": 1,
    "GenerateKeyPair": 1,
    "RemovePatches": 2,
    "DismissSuggestionHunks": 1,
    "AddPublicKey": 1,
    "WatchWorkspace": 1,
    "RequestReview": 1,
    "UpdateACL": 1,
    "ArchiveNotifications": 1,
    "AddUserToCodebase": 1,
    "VerifyEmail": 2,
    "UpdateUser": 2,
    "DeleteComment": 1,
    "LandWorkspaceChange": 2,
    "Comment": 3,
    "Workspaces": 2,
    "ResolvedBy": 1,
    "Notifications": 1,
    "UpdateComment": 1,
    "CreateComment": 1,
    "UpdateCodebase": 1,
    "ReportWorkspacePresence": 1,
    "DismissSuggestion": 1,
    "UpdateOrganization": 1,
    "UpdatedWorkspacesStatuses": 1,
    "CreateOrUpdateGitHubPullRequest": 1,
    "TriggerInstantIntegration": 1,
    "PushCodebase": 1,
    "UpdatedGitHubPullRequest": 1,
}
analyze(folder, words)

                                Word  Count Search  Count Markup      Ratio
0                           Activity            43             1  43.000000
1                            Comment            94             3  31.333333
2                LandWorkspaceChange            22             2  11.000000
3                            Members            19             2   9.500000
4                       AddPublicKey             7             1   7.000000
5                         ResolvedBy             6             1   6.000000
6                            Changes             6             1   6.000000
7                 UpdateInstallation             4             1   4.000000
8                        DownloadZip             4             1   4.000000
9    CreateOrUpdateGitHubPullRequest             4             1   4.000000
10                     CreateComment             4             1   4.000000
11                     RemovePatches             7             2   3.500000
12                       VerifyEmail             7             2   3.500000
13  UpdatedGitHubPullRequestStatuses             3             1   3.000000
14          UpdatedGitHubPullRequest             3             1   3.000000
15             SetupGitHubRepository             3             1   3.000000
16      CreateOrUpdateCodebaseRemote             3             1   3.000000
17           ReportWorkspacePresence             2             1   2.000000
18                    UpdateCodebase             2             1   2.000000
19                 DismissSuggestion             2             1   2.000000
20         UpdatedWorkspacesStatuses             2             1   2.000000
21                     UpdateComment             2             1   2.000000
22                     Notifications             2             1   2.000000
23         TriggerInstantIntegration             2             1   2.000000
24                        Workspaces             4             2   2.000000
25                      PushCodebase             2             1   2.000000
26                UpdateOrganization             2             1   2.000000
27                      Integrations             2             1   2.000000
28                     DeleteComment             2             1   2.000000
29                        UpdateUser             4             2   2.000000
30                 AddUserToCodebase             2             1   2.000000
31              ArchiveNotifications             2             1   2.000000
32                     RequestReview             2             1   2.000000
33                    WatchWorkspace             2             1   2.000000
34            DismissSuggestionHunks             2             1   2.000000
35                   GenerateKeyPair             2             1   2.000000
36             UpdatedWorkspaceDiffs             2             1   2.000000
37                       UpdatedView             2             1   2.000000
38                 UpdatedSuggestion             2             1   2.000000
39               UpdatedOrganization             2             1   2.000000
40                      LastUsedView             4             2   2.000000
41                 DeleteIntegration             2             1   2.000000
42                      PullCodebase             2             1   2.000000
43                         UpdateACL             2             1   2.000000

   Word  Count Search  Count Markup     Ratio
0  MEAN      6.795455      1.204545  4.609848

In [113]:
folder = 'e:\\phd\\test_repos_graphql2\\toolkit-for-cardano\\'
words = {
    "WalletDelegate": 1,
    "WalletRegister": 1,
    "WalletFund": 1,
    "WalletCreate": 1,
    "SendFunds": 1,
    "TxSubmit": 1,
    "TxSign": 1,
    "TxBuild": 1,
    "Mint": 1,
    "Wallets": 1,
    "Utxos": 2,
    "TxFee": 1,
}
analyze(folder, words)

              Word  Count Search  Count Markup  Ratio
0            Utxos            22             2   11.0
1             Mint             9             1    9.0
2   WalletDelegate             2             1    2.0
3   WalletRegister             2             1    2.0
4         TxSubmit             2             1    2.0
5           TxSign             2             1    2.0
6            TxFee             2             1    2.0
7       WalletFund             1             1    1.0
8     WalletCreate             1             1    1.0
9        SendFunds             1             1    1.0
10         TxBuild             1             1    1.0
11         Wallets             1             1    1.0

   Word  Count Search  Count Markup     Ratio
0  MEAN      3.833333      1.083333  2.916667

In [114]:
global_array

array([2.50000000e+01, 2.10000000e+01, 2.10000000e+01, 1.10000000e+01,
       1.00000000e+01, 1.00000000e+01, 9.00000000e+00, 9.00000000e+00,
       9.00000000e+00, 9.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       4.70000000e+01, 1.45000000e+01, 1.10000000e+01, 9.50000000e+00,
       8.50000000e+00, 8.00000000e+00, 6.00000000e+00, 6.00000000e+00,
       3.55000000e+01, 1.15000000e+01, 1.10000000e+01, 1.00000000e+01,
       8.50000000e+00, 8.00000000e+00, 8.00000000e+00, 8.00000000e+00,
       7.50000000e+00, 2.19000000e+02, 1.23000000e+02, 1.11000000e+02,
       3.50000000e+01, 2.70000000e+01, 2.60000000e+01, 1.20000000e+01,
       1.10000000e+01, 8.00000000e+00, 7.00000000e+00, 7.00000000e+00,
       7.00000000e+00, 6.00000000e+00, 5.00000000e+00, 5.00000000e+00,
       5.00000000e+00, 5.00000000e+00, 4.50000000e+00, 4.00000000e+00,
       4.00000000e+00, 4.00000000e+00, 4.00000000e+00, 4.00000000e+00,
       4.00000000e+00, 4.00000000e+00, 3.66666667e+00, 3.50000000e+00,
       3.50000000e+00, 3.50000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 5.60000000e+01,
       3.20000000e+01, 2.60000000e+01, 8.00000000e+00, 7.00000000e+00,
       5.00000000e+00, 4.00000000e+00, 4.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.48500000e+02,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 2.57700000e+03, 6.60000000e+02, 3.79000000e+02,
       3.71000000e+02, 2.70500000e+02, 1.80000000e+02, 1.64000000e+02,
       1.49500000e+02, 1.43000000e+02, 1.22000000e+02, 9.90000000e+01,
       8.20000000e+01, 6.60000000e+01, 6.10000000e+01, 5.50000000e+01,
       5.40000000e+01, 5.40000000e+01, 4.10000000e+01, 3.90000000e+01,
       3.70000000e+01, 3.30000000e+01, 3.10000000e+01, 2.70000000e+01,
       2.60000000e+01, 2.10000000e+01, 1.70000000e+01, 1.20000000e+01,
       1.20000000e+01, 1.20000000e+01, 1.00000000e+01, 1.00000000e+01,
       9.50000000e+00, 9.00000000e+00, 9.00000000e+00, 8.00000000e+00,
       8.00000000e+00, 8.00000000e+00, 8.00000000e+00, 7.00000000e+00,
       7.00000000e+00, 7.00000000e+00, 4.00000000e+00, 4.00000000e+00,
       3.00000000e+00, 6.36400000e+03, 1.44600000e+03, 1.09600000e+03,
       1.04900000e+03, 7.70000000e+02, 7.12000000e+02, 4.42000000e+02,
       4.26000000e+02, 4.20000000e+02, 3.87000000e+02, 3.45000000e+02,
       3.41000000e+02, 3.19000000e+02, 2.53000000e+02, 2.46000000e+02,
       2.19000000e+02, 1.88000000e+02, 1.82000000e+02, 1.69000000e+02,
       1.68000000e+02, 1.56000000e+02, 1.48000000e+02, 1.46000000e+02,
       1.31000000e+02, 1.05000000e+02, 8.20000000e+01, 8.20000000e+01,
       7.30000000e+01, 7.20000000e+01, 6.00000000e+01, 5.90000000e+01,
       5.10000000e+01, 5.10000000e+01, 4.70000000e+01, 3.20000000e+01,
       2.30000000e+01, 2.30000000e+01, 1.80000000e+01, 1.70000000e+01,
       1.70000000e+01, 1.70000000e+01, 1.70000000e+01, 1.60000000e+01,
       1.60000000e+01, 1.40000000e+01, 1.20000000e+01, 1.20000000e+01,
       9.00000000e+00, 8.00000000e+00, 4.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 8.50000000e+01,
       7.50000000e+01, 5.40000000e+01, 3.75000000e+01, 3.60000000e+01,
       2.60000000e+01, 5.00000000e+00, 3.50000000e+00, 3.00000000e+00,
       3.00000000e+00, 2.00000000e+00, 2.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.09000000e+02, 9.50000000e+01,
       5.40000000e+01, 4.40000000e+01, 4.40000000e+01, 7.00000000e+00,
       4.63000000e+02, 3.53000000e+02, 1.80000000e+02, 5.50000000e+01,
       7.00000000e+00, 6.00000000e+00, 4.00000000e+00, 4.00000000e+00,
       3.50000000e+00, 3.50000000e+00, 3.50000000e+00, 3.00000000e+00,
       3.00000000e+00, 3.00000000e+00, 3.00000000e+00, 2.50000000e+00,
       2.50000000e+00, 1.10000000e+01, 1.10000000e+01, 1.00000000e+01,
       1.00000000e+01, 7.00000000e+00, 7.00000000e+00, 6.00000000e+00,
       5.00000000e+00, 4.30000000e+01, 3.13333333e+01, 1.10000000e+01,
       9.50000000e+00, 7.00000000e+00, 6.00000000e+00, 6.00000000e+00,
       4.00000000e+00, 4.00000000e+00, 4.00000000e+00, 4.00000000e+00,
       3.50000000e+00, 3.50000000e+00, 3.00000000e+00, 3.00000000e+00,
       3.00000000e+00, 3.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 1.10000000e+01, 9.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00])

In [135]:
data = global_array
# Определяем границы интервалов
bins = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30, 50, 100, 7000]

# Задаем названия интервалов
intervals = [
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
    '11-15', '16-20', '21-30', '31-50', '51-100', '>100'
]

# Считаем количество элементов в каждом интервале
counts, _ = np.histogram(data, bins=bins)

# Создаем словарь {интервал: количество}
result = dict(zip(intervals, counts))
print(result)

{'1': 56, '2': 50, '3': 22, '4': 20, '5': 7, '6': 7, '7': 13, '8': 13, '9': 11, '10': 24, '11-15': 8, '16-20': 12, '21-30': 17, '31-50': 22, '51-100': 43, '>100': 0}

In [150]:
print(len(data[data==1]))
print(len(data[(data>1)&(data<=4)]))
print(len(data[(data>5)&(data<=10)]))
print(len(data[(data>10)]))

56
91
51
119