In [35]:
import os
import re
import pandas as pd

In [40]:
def count_words_in_go_files(folder_path, words_dict):
    word_search_counts = {word: 0 for word in words_dict.keys()}
    word_markup_counts = words_dict.copy()
    
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, words_dict.keys())) + r')\b')
    
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith('.go'):
                file_path = os.path.join(root, file)
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        matches = pattern.findall(content)
                        for word in matches:
                            word_search_counts[word] += 1
                except (UnicodeDecodeError, PermissionError) as e:
                    print(f"Ошибка при обработке файла {file_path}: {e}")
    
    # Создаем DataFrame
    df = pd.DataFrame({
        'Word': list(word_search_counts.keys()),
        'Count Search': list(word_search_counts.values()),
        'Count Markup': [word_markup_counts[word] for word in word_search_counts.keys()]
    })
    
    # Вычисляем Ratio
    df['Ratio'] = df['Count Search'] / df['Count Markup']
    
    # Сортируем по Ratio (по убыванию)
    df_sorted = df.sort_values(by='Ratio', ascending=False)
    df_sorted.reset_index(drop=True, inplace=True)
    
    return df_sorted

In [41]:
def analyze(folder, words):
    result_df = count_words_in_go_files(folder, words)

    mean_row = pd.DataFrame({
        'Word': ['MEAN'],
        'Count Search': [result_df['Count Search'].mean()],
        'Count Markup': [result_df['Count Markup'].mean()],
        'Ratio': [result_df['Ratio'].mean()]
    })

    display(result_df)
    display(mean_row)

In [42]:
folder = 'e:\\phd\\test_repos\\backend\\fsm-gateway\\'
words = {
    "GetOrderById": 1, 
    "GetSession": 1, 
    "GetDocumentData": 1,
    "GetDocumentText": 1,
    "GetConsentList": 1,
    "StartSession": 1,
    "SendDocumentData": 1,
    "FinishSession": 1,
    "Logout": 1,
    "StartAuthSessionByPhone": 1,
    "GetJwtByPhoneCode": 1,
    "GetJwtByRefreshToken": 1
}
analyze(folder, words)

                       Word  Count Search  Count Markup  Ratio
0      GetJwtByRefreshToken            25             1   25.0
1   StartAuthSessionByPhone            21             1   21.0
2         GetJwtByPhoneCode            21             1   21.0
3                GetSession            11             1   11.0
4           GetDocumentData            10             1   10.0
5              StartSession            10             1   10.0
6           GetDocumentText             9             1    9.0
7            GetConsentList             9             1    9.0
8          SendDocumentData             9             1    9.0
9             FinishSession             9             1    9.0
10             GetOrderById             4             1    4.0
11                   Logout             1             1    1.0

   Word  Count Search  Count Markup      Ratio
0  MEAN     11.583333           1.0  11.583333

In [46]:
folder = 'e:\\phd\\test_repos\\LP\\delivery-offering\\'
words = {
    "DeliveryTimeslots": 2, 
    "DeliveryTimeslot": 2, 
    "DeliveryTypes": 2, 
    "ReserveDeliveryTimeslot": 2,
    "LookupDeliveryOffers": 2,
    "DeliveryOfferByID": 2,
    "AcceptDeliveryOffer": 2,
    "ValidateDeliveryOffer": 2,
}
analyze(folder, words)

                      Word  Count Search  Count Markup  Ratio
0         DeliveryTimeslot            94             2   47.0
1            DeliveryTypes            29             2   14.5
2     LookupDeliveryOffers            22             2   11.0
3      AcceptDeliveryOffer            19             2    9.5
4        DeliveryOfferByID            17             2    8.5
5  ReserveDeliveryTimeslot            16             2    8.0
6        DeliveryTimeslots            12             2    6.0
7    ValidateDeliveryOffer            12             2    6.0

   Word  Count Search  Count Markup    Ratio
0  MEAN        27.625           2.0  13.8125

In [49]:
folder = 'e:\\phd\\test_repos\\LP\\warehouses\\'
words = {
    "TerminateWarehouses": 2, 
    "UpdateWarehouses": 2, 
    "CreateWarehouses": 2, 
    "Warehouses": 2,
}
analyze(folder, words)

                  Word  Count Search  Count Markup  Ratio
0           Warehouses            71             2   35.5
1     UpdateWarehouses            23             2   11.5
2     CreateWarehouses            22             2   11.0
3  TerminateWarehouses            20             2   10.0

   Word  Count Search  Count Markup  Ratio
0  MEAN          34.0           2.0   17.0

In [51]:
folder = 'e:\\phd\\test_repos\\LP\\channel-profile\\'
words = {
    "CreateChannelProfile": 2, 
    "UpdateChannelProfile": 2, 
    "DeleteChannelProfile": 2, 
    "ChannelProfiles": 2,
    "ChannelsByFilter": 2,
}
analyze(folder, words)

                   Word  Count Search  Count Markup  Ratio
0      ChannelsByFilter            17             2    8.5
1  CreateChannelProfile            16             2    8.0
2  UpdateChannelProfile            16             2    8.0
3  DeleteChannelProfile            16             2    8.0
4       ChannelProfiles            15             2    7.5

   Word  Count Search  Count Markup  Ratio
0  MEAN          16.0           2.0    8.0

In [61]:
folder = 'e:\\phd\\test_repos\\modules\\'
words = {
    "CompleteFollowup": 1, 
    "ReAssignFollowup": 2,
    "RemovePharmacy": 1,
    "SetABVariant": 1,
    "BlockPatient": 1,
    "SetMediaRead": 1,
    "ValidateAppointmentInsurance": 3,
    "UpdateProviderInsurance": 1,
    "EditStateCompanies": 1,
    "UpdateEncounterScreenedStatus": 1,
    "StartPaymentTransaction": 1,
    "SubscribeToPhoneCallEvents": 1,
    "SetAppointmentType": 1,
    "MakeCardDefault": 2,
    "DeletePatientNote": 1,
    "UpdatePatientNote": 1,
    "SetVisitTypeOrders": 2,
    "SetVisitTypeVisibility": 2,
    "AddICD10MedicalCode": 2,
    "AddMedicalCodes": 1,
    "InviteClient": 1,
    "DeleteEvent": 1,
    "NeedFollowup": 1,
    "TwilioInfo": 1,
    "CurrentTime": 1,
    "Person": 1,
    "PHIData": 1,
    "Clients": 1,
    "Messages": 1,
    "PastVisits": 1,
    "Appointment": 1,
    "CheckInData": 1,
    "NoteTemplate": 1,
    "VisitType": 1,
    "ScheduleVisit": 1,
    "UpdateAvailability": 1,
    "AssignQuestionnaire": 1,
    "PublishForm": 1,
    "LoadFollowupByPatients": 1,
    "InsuranceCosts": 1,
    "PatientDetails": 1,
    "ConsentForms": 1
}
analyze(folder, words)

                             Word  Count Search  Count Markup       Ratio
0                     Appointment           219             1  219.000000
1                       VisitType           123             1  123.000000
2                          Person           111             1  111.000000
3                        Messages            35             1   35.000000
4                         PHIData            27             1   27.000000
5                    NoteTemplate            26             1   26.000000
6                     CheckInData            12             1   12.000000
7                  PatientDetails            11             1   11.000000
8                      TwilioInfo             8             1    8.000000
9               DeletePatientNote             7             1    7.000000
10        StartPaymentTransaction             7             1    7.000000
11              UpdatePatientNote             7             1    7.000000
12                    CurrentTime             6             1    6.000000
13             UpdateAvailability             5             1    5.000000
14                   NeedFollowup             5             1    5.000000
15                        Clients             5             1    5.000000
16             SetAppointmentType             5             1    5.000000
17                MakeCardDefault             9             2    4.500000
18            AddICD10MedicalCode             8             2    4.000000
19                 RemovePharmacy             4             1    4.000000
20                   BlockPatient             4             1    4.000000
21     SubscribeToPhoneCallEvents             4             1    4.000000
22             EditStateCompanies             4             1    4.000000
23        UpdateProviderInsurance             4             1    4.000000
24                   SetABVariant             4             1    4.000000
25   ValidateAppointmentInsurance            11             3    3.666667
26         SetVisitTypeVisibility             7             2    3.500000
27               ReAssignFollowup             7             2    3.500000
28             SetVisitTypeOrders             7             2    3.500000
29                    PublishForm             2             1    2.000000
30            AssignQuestionnaire             2             1    2.000000
31         LoadFollowupByPatients             1             1    1.000000
32                 InsuranceCosts             1             1    1.000000
33               CompleteFollowup             1             1    1.000000
34                    DeleteEvent             1             1    1.000000
35                  ScheduleVisit             1             1    1.000000
36                     PastVisits             1             1    1.000000
37                   InviteClient             1             1    1.000000
38                AddMedicalCodes             1             1    1.000000
39  UpdateEncounterScreenedStatus             1             1    1.000000
40                   SetMediaRead             1             1    1.000000
41                   ConsentForms             1             1    1.000000

   Word  Count Search  Count Markup      Ratio
0  MEAN     16.833333      1.166667  16.206349

In [63]:
folder = 'e:\\phd\\test_repos_graphql2\\boost\\'
words = {
    "DealUpdate": 1, 
    "StorageAskUpdate": 1, 
    "FundsMoveToEscrow": 1, 
    "DealFailPaused": 1, 
    "DealRetryPaused": 1, 
    "DealCancel": 1, 
    "Mpool": 1, 
    "FundsLogs": 1, 
    "ProposalLogs": 1, 
    "LegacyDeals": 1, 
    "Deals": 1, 
    "LegacyDeal": 1, 
    "Deal": 2, 
    "DealNew": 1, 
    "DealsCount": 1, 
    "StorageAsk": 1, 
    "DealPublishNow": 1, 
    "DealPublish": 1,
    "Epoch": 1,
    "Funds": 1,
    "ProposalLogsCount": 1,
    "SealingPipeline": 1,
    "Storage": 1,
    "Transfers": 1,
    
}
analyze(folder, words)

                 Word  Count Search  Count Markup  Ratio
0               Deals            56             1   56.0
1          StorageAsk            32             1   32.0
2             Storage            26             1   26.0
3                Deal            16             2    8.0
4               Epoch             7             1    7.0
5        ProposalLogs             5             1    5.0
6           FundsLogs             4             1    4.0
7           Transfers             4             1    4.0
8             DealNew             2             1    2.0
9         DealPublish             2             1    2.0
10              Funds             2             1    2.0
11    SealingPipeline             2             1    2.0
12              Mpool             1             1    1.0
13        LegacyDeals             1             1    1.0
14         DealCancel             1             1    1.0
15         LegacyDeal             1             1    1.0
16   StorageAskUpdate             1             1    1.0
17         DealsCount             1             1    1.0
18    DealRetryPaused             1             1    1.0
19     DealPublishNow             1             1    1.0
20     DealFailPaused             1             1    1.0
21  ProposalLogsCount             1             1    1.0
22  FundsMoveToEscrow             1             1    1.0
23         DealUpdate             1             1    1.0

   Word  Count Search  Count Markup  Ratio
0  MEAN      7.083333      1.041667   6.75

In [64]:
folder = 'e:\\phd\\test_repos_graphql2\\bramble\\'
words = {
    "UploadGadgetFile": 1, 
    "UploadGizmoFile": 1, 
    "Gizmo": 2, 
    "Gizmos": 2, 
    "Delay": 1, 
    "Gizmos": 2, 
    "RandomGizmo": 1,
}
analyze(folder, words)

               Word  Count Search  Count Markup  Ratio
0             Gizmo           297             2  148.5
1  UploadGadgetFile             1             1    1.0
2   UploadGizmoFile             1             1    1.0
3            Gizmos             2             2    1.0
4             Delay             1             1    1.0
5       RandomGizmo             1             1    1.0

   Word  Count Search  Count Markup      Ratio
0  MEAN          50.5      1.333333  25.583333

In [66]:
folder = 'e:\\phd\\test_repos_graphql2\\circuit\\'
words = {
    "Secrets": 2, 
    "Services": 2, 
    "Releases": 2, 
    "EnvsDeployedIn": 2, 
    "Features": 2, 
    "GetGitCommits": 1, 
    "BookmarkProject": 1, 
    "UpdateProjectEnvironments": 1, 
    "UpdateUserPermissions": 1, 
    "DeleteProjectExtension": 1, 
    "UpdateProjectExtension": 1, 
    "CreateProjectExtension": 1, 
    "DeleteExtension": 1, 
    "UpdateExtension": 1, 
    "CreateExtension": 1, 
    "ImportSecrets": 1, 
    "DeleteSecret": 1, 
    "UpdateSecret": 1, 
    "CreateSecret": 1, 
    "DeleteEnvironment": 1,
    "UpdateEnvironment": 1, 
    "CreateEnvironment": 1, 
    "DeleteServiceSpec": 1, 
    "UpdateServiceSpec": 1, 
    "CreateServiceSpec": 1, 
    "ImportServices": 1, 
    "DeleteService": 1, 
    "UpdateService": 1, 
    "CreateService": 1, 
    "StopRelease": 1,
    "CreateRelease": 1, 
    "UpdateProject": 1, 
    "CreateProject": 1, 
    "Permissions": 1, 
    "ReleaseExtensions": 1, 
    "ProjectExtensions": 1, 
    "Extensions": 1, 
    "Secret": 1, 
    "ExportSecrets": 1, 
    "Environments": 1, 
    "ServiceSpecs": 1, 
    "Users": 1, 
    "User": 1, 
    "Bookmarked": 1, 
}
analyze(folder, words)

                         Word  Count Search  Count Markup   Ratio
0                        User          2577             1  2577.0
1                      Secret           660             1   660.0
2                  Extensions           379             1   379.0
3                 Permissions           371             1   371.0
4                    Services           541             2   270.5
5               CreateProject           180             1   180.0
6           CreateEnvironment           164             1   164.0
7                     Secrets           299             2   149.5
8               CreateService           143             1   143.0
9                       Users           122             1   122.0
10               CreateSecret            99             1    99.0
11              UpdateService            82             1    82.0
12              UpdateProject            66             1    66.0
13            CreateExtension            61             1    61.0
14          CreateServiceSpec            55             1    55.0
15               UpdateSecret            54             1    54.0
16     CreateProjectExtension            54             1    54.0
17          UpdateEnvironment            41             1    41.0
18              DeleteService            39             1    39.0
19              CreateRelease            37             1    37.0
20               Environments            33             1    33.0
21                   Features            62             2    31.0
22               DeleteSecret            27             1    27.0
23          ProjectExtensions            26             1    26.0
24          DeleteEnvironment            21             1    21.0
25                 Bookmarked            17             1    17.0
26             ImportServices            12             1    12.0
27          ReleaseExtensions            12             1    12.0
28                StopRelease            12             1    12.0
29              ImportSecrets            10             1    10.0
30  UpdateProjectEnvironments            10             1    10.0
31                   Releases            19             2     9.5
32      UpdateUserPermissions             9             1     9.0
33          DeleteServiceSpec             9             1     9.0
34     DeleteProjectExtension             8             1     8.0
35     UpdateProjectExtension             8             1     8.0
36          UpdateServiceSpec             8             1     8.0
37            BookmarkProject             8             1     8.0
38            DeleteExtension             7             1     7.0
39              ExportSecrets             7             1     7.0
40            UpdateExtension             7             1     7.0
41               ServiceSpecs             4             1     4.0
42             EnvsDeployedIn             8             2     4.0
43              GetGitCommits             3             1     3.0

   Word  Count Search  Count Markup       Ratio
0  MEAN    144.795455      1.113636  134.238636

In [67]:
folder = 'e:\\phd\\test_repos_graphql2\\core-geth\\'
words = {
    "SendRawTransaction": 2,
    "Logs": 2,
    "Transaction": 2,
    "Blocks": 1,
    "Block": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "EstimateGas": 1,
    "Call": 1,
    "Account": 1,
    "OmmerAt": 1,
    "Miner": 1,
    "CreatedContract": 1,
    "To": 1,
    "From": 1,
    "Account": 1,
    "Storage": 1,
    "Status": 1,
    "Nonce": 1,
    "Hash": 1,
    "TransactionCount": 1,
    "ChainID": 1,
    "MaxPriorityFeePerGas": 1,
    "GasPrice": 1,
    "Transactions": 1,
    "ExcessBlobGas": 1,
    "BlobGasUsed": 1,
    "Withdrawals": 1,
    "WithdrawalsRoot": 1,
    "Raw": 1,
    "RawHeader": 1,
    "TotalDifficulty": 1,
    "LogsBloom": 1,
    "ExtraData": 1,
    "Ommers": 1,
    "OmmerCount": 1,
    "OmmerHash": 1,
    "ReceiptsRoot": 1,
    "StateRoot": 1,
    "TransactionsRoot": 1,
    "MixHash": 1,
    "Timestamp": 1,
    "Difficulty": 1,
    "Parent": 1,
    "NextBaseFeePerGas": 1,
    "BaseFeePerGas": 1,
    "GasUsed": 1,
    "GasLimit": 1,
    "Number": 1,
    "YParity": 1,
    "AccessList": 1,
    "Type": 1,
    "BlobGasPrice": 1,
    "CumulativeGasUsed": 1,
    "Index": 1,
    "Value": 1,
    "EffectiveTip": 1,
    "BlobVersionedHashes": 1,
    "MaxFeePerBlobGas": 1,
    "MaxFeePerGas": 1,
    "EffectiveGasPrice": 1,
    "Gas": 1,
    "InputData": 1
}
analyze(folder, words)

                    Word  Count Search  Count Markup   Ratio
0                   Hash          6364             1  6364.0
1                 Number          1446             1  1446.0
2                  Value          1096             1  1096.0
3                   Type          1049             1  1049.0
4                  Block           770             1   770.0
5                  Nonce           712             1   712.0
6                     To           485             1   485.0
7                Account           442             1   442.0
8            Transaction           852             2   426.0
9                    Gas           420             1   420.0
10            Difficulty           387             1   387.0
11          Transactions           345             1   345.0
12              GasLimit           341             1   341.0
13              GasPrice           319             1   319.0
14                  From           295             1   295.0
15               Storage           253             1   253.0
16               ChainID           246             1   246.0
17               GasUsed           219             1   219.0
18             Timestamp           188             1   188.0
19            AccessList           182             1   182.0
20                  Call           169             1   169.0
21                Status           168             1   168.0
22                 Index           156             1   156.0
23           Withdrawals           148             1   148.0
24         ExcessBlobGas           146             1   146.0
25           BlobGasUsed           131             1   131.0
26                 Miner           105             1   105.0
27                  Logs           164             2    82.0
28          MaxFeePerGas            82             1    82.0
29             ExtraData            73             1    73.0
30  MaxPriorityFeePerGas            72             1    72.0
31                Parent            60             1    60.0
32                Blocks            59             1    59.0
33     CumulativeGasUsed            51             1    51.0
34             StateRoot            51             1    51.0
35                   Raw            47             1    47.0
36         BaseFeePerGas            32             1    32.0
37     EffectiveGasPrice            23             1    23.0
38             LogsBloom            23             1    23.0
39       TotalDifficulty            18             1    18.0
40                Ommers            17             1    17.0
41           EstimateGas            17             1    17.0
42          BlobGasPrice            17             1    17.0
43   BlobVersionedHashes            17             1    17.0
44               MixHash            16             1    16.0
45          ReceiptsRoot            16             1    16.0
46       WithdrawalsRoot            14             1    14.0
47               YParity            12             1    12.0
48             OmmerHash            12             1    12.0
49      TransactionCount             9             1     9.0
50      MaxFeePerBlobGas             8             1     8.0
51      TransactionsRoot             4             1     4.0
52          EffectiveTip             2             1     2.0
53    SendRawTransaction             4             2     2.0
54     NextBaseFeePerGas             2             1     2.0
55            OmmerCount             2             1     2.0
56             RawHeader             2             1     2.0
57       CreatedContract             2             1     2.0
58               OmmerAt             2             1     2.0
59             InputData             2             1     2.0

   Word  Count Search  Count Markup  Ratio
0  MEAN         306.1          1.05  297.6